Feature: Register new user
vibely-social/cg-vibely-social-service pull request #6
Opened 2023-08-10 12:22 UTC by chphungphat

Other changes:
- move authenticate method into UserServiceImpl
- PasswordEncoder move into new class BeanContext to prevent circular injection
- Add regex for email, password, gender, phone number into application.properties
- Add back in sql scripts.
- Add JwtAuthEntryPoint to handle exception
- Change security filter to permit all for all api request for easier testing

2023-08-10 13:02 UTC, ChungNguyenVr912 requested changes

2023-08-10 13:02 UTC, ChungNguyenVr912 commented on src/main/java/com/cg_vibely_social_service/entity/Gender.java
not entity

2023-08-10 13:02 UTC, ChungNguyenVr912 commented on src/main/java/com/cg_vibely_social_service/dto/converter/UserConverter.java
> +public class UserConverter {
implement interface for DI

2023-08-11 04:31 UTC, ChungNguyenVr912 approved these changes
look better

2023-08-11 04:34 UTC, MinhTam1509 approved these changes
that's good

2023-08-11 05:29 UTC, HuyVu18 approved these changes

2023-08-11 05:31 UTC, merged